spring:
  application:
    name: chat-storage-ms
  datasource:
#    url: jdbc:mysql://${DB_HOST_NAME}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST_NAME:localhost}:${DB_PORT:3306}/${DB_NAME:dev}
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
server:
  port: 8080
